<?php
session_start();
if(!isset($_SESSION['email_id'])){
        session_start();
        session_unset();
        session_destroy();
    }else{
        session_unset();
        session_destroy();
    }
    header("location:index.php");
?>